#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE}")" && pwd)"

IMAGE=$SCRIPT_DIR/ubuntu25.img
EDK2_CODE=/opt/homebrew/share/qemu/edk2-aarch64-code.fd
EDK2_VARS=$SCRIPT_DIR/edk2-aarch64-vars.fd

qemu-system-aarch64 \
  -machine virt,accel=hvf \
  -cpu host \
  -smp 4 \
  -m 8G \
  -drive file=$IMAGE,format=qcow2,if=virtio \
  -drive file=$EDK2_CODE,if=pflash,readonly=on,format=raw \
  -drive file=$EDK2_VARS,if=pflash,format=raw \
  -device virtio-gpu-pci \
  -device virtio-keyboard \
  -netdev user,id=net0,hostfwd=tcp::2222-:22 \
  -device virtio-net-pci,netdev=net0 \
  -boot menu=on \
	-device qemu-xhci \
	-device usb-kbd \
  -device usb-mouse \
	-display cocoa $@
